### ISSUE TITLE
'Go to Test' from Test Explorer window opens the auto-generated C# backing file instead of the .feature file 

### ISSUE THREAD

**Issue by mattrenshaw94** [SpecFlowOSS/SpecFlow.VS#119]
### Used Visual Studio

Visual Studio 2022

### Are the latest Visual Studio updates installed?

Yes

### Issue Description

When navigating to a test by double clicking it in the test explorer, the C# backing file for the test is being opened instead of the feature file. This only started occurring when updating to the latest preview version of Visual Studio 2022 (Version 17.5.0 Preview 2.0). 

### Steps to Reproduce

Visual Studio version: 2022 Version 17.5.0 Preview 2.0
Specflow version: 3.9.74
.NET version: 6.0
Specflow extension version: 2022.1.89.53862

This is recreate-able by:

1. Create a new specflow project in Visual Studio 
2. Ensure the Test Explorer window is open 
3. Build the project to discover all tests
4. Double click the 'AddTwoNumbers' test that was created as part of the project OR right click the test in the Test Explorer, and select 'Go to Test'

Expected: 
The Calculator.feature file is opened

Actual: 
The Calculator.feature.cs file is opened

**Comment by autosonic** [comment]
This is still a problem in Visual Studio 17.5.1.
SpecFlow extension version 2022.1.91.26832.
