### ISSUE TITLE
InvokeDiscovery: Error during binding discovery / It was not possible to find any compatible framework version

### ISSUE THREAD

**Issue by rent-a-developer** [SpecFlowOSS/SpecFlow.VS#13]
I am getting the following error message in Visual Studio 2022 in the output from SpecFlow:

```
Warning: InvokeDiscovery: Error during binding discovery. 
Command executed:
  E:\Git\Sources\Tests\SpecTests\..\..\..\Output\Tests> C:\Program Files\dotnet\dotnet.exe exec C:\USERS\User\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\17.0_972784BA\EXTENSIONS\BHTXN4QW.IOB\Connectors\V3-net6.0\specflow-vs.dll discovery E:\Git\Sources\Tests\SpecTests\..\..\..\Output\Tests\SpecTests.dll E:\Git\Sources\Tests\SpecTests\specflow.json
Exit code: <not executed>
Message: 
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '6.0.0-rc.1.21451.13' was not found.
  - The following frameworks were found:
      2.1.29 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.1.30 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      3.1.18 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      3.1.20 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      5.0.9 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      5.0.10 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      5.0.11 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      6.0.0-preview.7.21377.19 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.
```

It seems SpecFlow is trying to use the .NET 6 version of specflow-vs.dll.
However, the Project has the target framework .NET 5:
```
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net5.0-windows</TargetFramework>
		...
	</PropertyGroup>
	...
</Project>
```

I am using SpecFlow Version 3.9.22.

I am using the following SpecFlow VS extension:
SpecFlow for Visual Studio 2022, Version 2021.0.198.7895.

Could it be that SpecFlow is confused because the project file specifies a OS specific target framework moniker ("net5.0-windows")?

Any help is highly appreciated!

**Comment by rent-a-developer** [comment]
Visual Studio automatically updated the SpecFlow VS Extension to Version 2021.0.199.10836 today.
Now I am getting this error again:

```
Info: OnActivityStarted: Starting Visual Studio Extension...
Info: CreateProjectScope: Initializing project: SpecTests
Info: StartRetryInitializeTimer: Project settings not available yet, retry in 5 seconds...
Info: OnSettingsInitialized: Project settings initialized: .NETCoreApp,Version=v5.0,SpecFlow:3.9.22,x64
Warning: InvokeDiscovery: Error during binding discovery. 
Command executed:
  E:\Git\Sources\Tests\SpecTests\..\..\..\Output\Tests> C:\Program Files\dotnet\dotnet.exe exec c:\users\User\appdata\local\microsoft\visualstudio\17.0_972784ba\extensions\ewy3cvt1.qms\Connectors\V3-net6.0\specflow-vs.dll discovery E:\Sources\Tests\SpecTests\..\..\..\Output\Tests\SpecTests.dll E:\Git\Sources\Tests\SpecTests\specflow.json
Exit code: <not executed>
Message: 
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '6.0.0-rc.2.21480.5' (x64) was not found.
  - The following frameworks were found:
      2.1.29 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.1.30 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      3.1.18 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      3.1.20 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      5.0.9 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      5.0.10 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      5.0.11 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      6.0.0-preview.7.21377.19 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      6.0.0-rc.1.21451.13 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.
```

I think there is something wrong in general:
In the global.json file (in the root directory of my solution), I explicitly have set the SDK version to 5.x:
```
{
    "sdk": {
        "version": "5.0.0",
        "rollForward": "latestMinor"
    }
}
```

If my understanding is correct, all build tools (including the SpecFlow Extension) should respect this setting and use the 5.x SDK.
However, the SpecFlow Extensions is using the 6.x SDK.

**Comment by patiqs** [comment]
This is not related to .net5 at all. The plugin is looking for the latest .net framework. 
The version of .net6 changed frequently in the last few weeks since .net6 was in development phase.
The error messages clearly shows that.
`The framework 'Microsoft.NETCore.App', version '**6.0.0-rc.1.21451.13**' was not found.
  - The following frameworks were found:
......
      6.0.0-preview.7.21377.19 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]`
`The framework 'Microsoft.NETCore.App', version '**6.0.0-rc.2.21480.5' (x64)** was not found.
  - The following frameworks were found:
......
      6.0.0-preview.7.21377.19 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      6.0.0-rc.1.21451.13 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]`

The next release of the plugin will be able to solve the issue, since we have the final .Net6.
Until then the solution is update your .net6 SDK to the latest

**Comment by mraming** [comment]
I'm having the exact same error when opening the project in VS 2022 with the latest extension and SpecFlow NuGet packages installed.

![image](https://user-images.githubusercontent.com/15705076/142015232-d2a762c4-6c9a-4c63-8d67-3054cb5e946e.png)

![image](https://user-images.githubusercontent.com/15705076/142015403-ac43dc98-8581-48f0-b5bd-392bee5884d7.png)

In addition, the feature.cs generation fails at compile-time, but no clear error message is being logged - not sure where I can find more log information or how to enable more verbose logging.

I'm willing to share the source code if that helps investigation - just send me a private message...

**Comment by rent-a-developer** [comment]
@patiqs I still think that, in case a SDK version is explicitly specified for the solution (see https://docs.microsoft.com/en-us/dotnet/core/tools/global-json), the SpecFlow extension should use that version.

**Comment by patiqs** [comment]
I released 2021.1.2 today. Can you validate?

**Comment by patiqs** [comment]
@rent-a-developer 
The extension uses a so called "connector" to collect the specflow related information from the compiled assembly of the project. This is why the new plugin is able to work with external assemblies and inherited stepdefinitinos etc.
This is why we have to rebuild the project, when the step definitions are modified.

These connectors are located  in c:\users\User\appdata\local\microsoft\visualstudio\<xxxx>\extensions\<yyyy>\Connectors\<zzzzz>\specflow-vs.dll

The error shows that this connector cannot be loaded because it is built with a newer version of .net. This is not related to the extension.
You can reproduce the issue with just simply execute the connector from its folder with "dotnet exec specflow-vs.dll" or "specflow-vs.exe" if exists

**Comment by rent-a-developer** [comment]
@patiqs The new release seems to be working fine! Thanks!

**Comment by mraming** [comment]
> I released 2021.1.2 today. Can you validate?

It's not working for me; I get the following error now in the SpecFlow output window:
```
Info: OnActivityStarted: Starting Visual Studio Extension...
Info: CreateProjectScope: Initializing project: SampleProjectName
Info: StartRetryInitializeTimer: Project settings not available yet, retry in 5 seconds...
Info: OnSettingsInitialized: Project settings initialized: .NETFramework,Version=v4.7.2,SpecFlow:3.9.40
Warning: InvokeDiscovery: Error during binding discovery. Unable to find connector: C:\USERS\XXXX.XXXX\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\17.0_2EB42BF2\EXTENSIONS\A31ZNUMQ.HBW\V1\specflow-vs.exe
Warning: InvokeDiscovery: The project bindings (e.g. step definitions) could not be discovered. Navigation, step completion and other features are disabled. 
  Please check the error message above and report to https://github.com/SpecFlowOSS/SpecFlow.VS/issues if you cannot fix.
```

**Comment by rent-a-developer** [comment]
I am getting the same error now too:

```
Info: OnActivityStarted: Starting Visual Studio Extension...
Info: CreateProjectScope: Initializing project: SpecTests
Info: OnSettingsInitialized: Project settings initialized: .NETCoreApp,Version=v5.0,SpecFlow:3.9.22,x64
Warning: InvokeDiscovery: Error during binding discovery. 
Command executed:
  E:\Sources\Tests\> C:\Program Files\dotnet\dotnet.exe exec C:\USERS\User\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\17.0_542C7510\EXTENSIONS\LP1PZAZA.SGI\V3-net6.0\specflow-vs.dll discovery E:\Sources\Tests\SpecTests.dll E:\Sources\Tests\specflow.json
Exit code: <not executed>
Message: 
The application to execute does not exist: 'C:\USERS\User\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\17.0_542C7510\EXTENSIONS\LP1PZAZA.SGI\V3-net6.0\specflow-vs.dll'
Warning: InvokeDiscovery: The project bindings (e.g. step definitions) could not be discovered. Navigation, step completion and other features are disabled. 
  Please check the error message above and report to https://github.com/SpecFlowOSS/SpecFlow.VS/issues if you cannot fix.
```

**Comment by patiqs** [comment]
It seems there vas a packaging problem with the release. I just released 2021.1.4.55204 with the fix. Can you please verify?
https://marketplace.visualstudio.com/items?itemName=TechTalkSpecFlowTeam.SpecFlowForVisualStudio2022

**Comment by mraming** [comment]
@patiqs Just did a 2-minute check: Downloaded and installed the new version. No more errors and I can navigate to the step definitions without problems. So things are looking good :-)

**Comment by patiqs** [comment]
Thank you for the feedback
