### ISSUE TITLE
SpecFlow templates come first in the "Add New Item" dialog

### ISSUE THREAD

**Issue by blemasle** [SpecFlowOSS/SpecFlow.VS#23]
Hi,

Since SpecFlow for VS2022, I noticed that SpecFlow items come first in the "Add New Item" dialog.
Most of the time, one does not want to add SpecFlow files but rather classes or interfaces. So they should come first as it was under VS 2019.

It also breaks the simple `Ctrl + Shift + A` + `Enter` to add a new class with only two keystrokes 😁 

![image](https://user-images.githubusercontent.com/5184737/142189490-e0671bad-aab9-4b51-92cd-c01c05a9b87f.png)
![image](https://user-images.githubusercontent.com/5184737/142189528-1524f1f2-85af-487e-a133-66869e087e2e.png)

VS 2022 v17.0.0
SpecFlow For Visual Studio 2022 v2021.0.200

**Comment by rent-a-developer** [comment]
You can also use Shift+Alt+C to create a new class.
I actually like it that the SpecFlow Feature File item comes first 😄

**Comment by blemasle** [comment]
I actually never tried that one before, but on my machine it displays the ClassView side panel.
But you're right, it's far more efficient with `Ctrl + Shift + C` 😁 

It seems to me that specflow files aren't the most frequent files added for most, so they shouldn't come in the first position. What if every other extension were to do the same ? That dialog would become a mess pretty quick 🙂

**Comment by patiqs** [comment]
We decided to lower the SortOrder of these items in the next release

**Comment by patiqs** [comment]
Modified in 2021.2.1
