### ISSUE TITLE
Scroll position in code editor is reset when reformatting feature file

### ISSUE THREAD

**Issue by rent-a-developer** [SpecFlowOSS/SpecFlow.VS#25]
Visual Studio 2022 (17.0.0), SpecFlow for Visual Studio 2022 (2021.0.200.43519).

When I reformat a feature file with the CTRL+K, D shortcut the scroll position in the editor window is reset to the first line (however, the caret keeps it's original position).
This is a bit distracting when I am reformatting a file that is a bit longer and I am editing something near the end of the file.

Please note:
In order to reproduce this issue you first need to change the file in such a way that the reformatting actually changes the file (e.g. add some unnecessary spaces to a cell in a table in the file and the press CTRL+K, D).

**Comment by alimogithub** [comment]
Hi David,
Thanks for raising this. I was able to replicate it and indeed it is distracting. We will take a look and update you
cheers

**Comment by rent-a-developer** [comment]
Hi,
any update on this issue?
It would be really nice to have this issue fixed.

**Comment by rent-a-developer** [comment]
Seems to be fixed in [v2022.1.4](https://github.com/SpecFlowOSS/SpecFlow.VS/releases/tag/v2022.1.4).

**Comment by rent-a-developer** [comment]
Sorry, I am a giddy goat.

I forgot to say:
Thank you very much for fixing this issue.
Working with SpecFlow in VS is even better now!
