### ISSUE TITLE
Error in the SpecFlow for Visual Studio 2022 extension version 2021.1.2.60110

### ISSUE THREAD

**Issue by Leticia-GX** [SpecFlowOSS/SpecFlow.VS#29]
When trying to get the definition of a  NEW step in a scenario : rigth buttom click+Define step. I get the message **"All steps have been defined in this file already"** (wich is not true since I have added a new step) and **this traces in the Output**

```
Info: OnActivityStarted: Starting Visual Studio Extension...
Info: CreateProjectScope: Initializing project: EcoTranslate.Api.Tests
Info: OnSettingsInitialized: Project settings initialized: .NETCoreApp,Version=v6.0,SpecFlow:3.9.40
Warning: InvokeDiscovery: Error during binding discovery. 
Command executed:
  C:\Users\Leticia\Source\Repos\EcoTranslate\EcoTranslate.Api\EcoTranslate.Api.Tests\bin\Debug\net6.0> C:\Program Files\dotnet\dotnet.exe exec C:\USERS\LETICIA\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\17.0_4B4D6D0A\EXTENSIONS\ROQVY2TY.ZUJ\V3-net6.0\specflow-vs.dll discovery C:\Users\Leticia\Source\Repos\EcoTranslate\EcoTranslate.Api\EcoTranslate.Api.Tests\bin\Debug\net6.0\EcoTranslate.Api.Tests.dll ""
Exit code: <not executed>
Message: 
The application to execute does not exist: 'C:\USERS\LETICIA\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\17.0_4B4D6D0A\EXTENSIONS\ROQVY2TY.ZUJ\V3-net6.0\specflow-vs.dll'
Warning: InvokeDiscovery: The project bindings (e.g. step definitions) could not be discovered. Navigation, step completion and other features are disabled. 
  Please check the error message above and report to https://github.com/SpecFlowOSS/SpecFlow.VS/issues if you cannot fix.
Warning: ShowProblem: User Notification: All steps have been defined in this file already.
Warning: ShowProblem: User Notification: All steps have been defined in this file already.

```

**Comment by idg10** [comment]
I'm getting a similar error message in the Output tab's SpecFlow section:

```
The application to execute does not exist: 'C:\USERS\IAN\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\17.0_535671E4\EXTENSIONS\O2GEUM0I.BUB\V3-net6.0\specflow-vs.dll'
```

This happened after NCrunch upgraded itself just now. The About dialog reports it as 4.11.0.2

**Comment by ALXANDR-B** [comment]
Same error occurred after VS 2022 updated automatically the Specflow extension.
First with error:
`Info: OnActivityStarted: Starting Visual Studio Extension...
Info: CreateProjectScope: Initializing project: SeleniumCSharpNUnitDotNetCore
Info: StartRetryInitializeTimer: Project settings not available yet, retry in 5 seconds...
Info: OnSettingsInitialized: Project settings initialized: .NETCoreApp,Version=v3.1,SpecFlow:3.9.22
Warning: InvokeDiscovery: Error during binding discovery. 
Command executed:
  C:\Users\lisbea1\source\repos\SeleniumCSharpNUnitDotNetCore\SeleniumCSharpNUnitDotNetCore\bin\Debug\netcoreapp3.1> C:\Program Files\dotnet\dotnet.exe exec C:\USERS\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\17.0_1D57F3C3\EXTENSIONS\5UKEWULW.MHR\V3-net6.0\specflow-vs.dll discovery C:\Users\lisbea1\source\repos\SeleniumCSharpNUnitDotNetCore\SeleniumCSharpNUnitDotNetCore\bin\Debug\netcoreapp3.1\SeleniumCSharpNUnitDotNetCore.dll ""
Exit code: <not executed>
Message: 
The application to execute does not exist: 'C:\USERS\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\17.0_1D57F3C3\EXTENSIONS\5UKEWULW.MHR\V3-net6.0\specflow-vs.dll'
Warning: InvokeDiscovery: The project bindings (e.g. step definitions) could not be discovered. Navigation, step completion and other features are disabled. 
  Please check the error message above and report to https://github.com/SpecFlowOSS/SpecFlow.VS/issues if you cannot fix.`  
  
Update my application to .net6.0 didn't helped:
`Info: CheckProjectSettings: Project settings updated: .NETCoreApp,Version=v6.0,SpecFlow:3.9.22
Warning: InvokeDiscovery: Error during binding discovery. 
Command executed:
  C:\Users\lisbea1\source\repos\SeleniumCSharpNUnitDotNetCore\SeleniumCSharpNUnitDotNetCore\bin\Debug\net6.0> C:\Program Files\dotnet\dotnet.exe exec C:\USERS\LISBEA1\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\17.0_1D57F3C3\EXTENSIONS\5UKEWULW.MHR\V3-net6.0\specflow-vs.dll discovery C:\Users\lisbea1\source\repos\SeleniumCSharpNUnitDotNetCore\SeleniumCSharpNUnitDotNetCore\bin\Debug\net6.0\SeleniumCSharpNUnitDotNetCore.dll ""
Exit code: <not executed>
Message: 
The application to execute does not exist: 'C:\USERS\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\17.0_1D57F3C3\EXTENSIONS\5UKEWULW.MHR\V3-net6.0\specflow-vs.dll'
Warning: InvokeDiscovery: The project bindings (e.g. step definitions) could not be discovered. Navigation, step completion and other features are disabled. 
  Please check the error message above and report to https://github.com/SpecFlowOSS/SpecFlow.VS/issues if you cannot fix.
`

**Comment by MacShack** [comment]
As reported in another issue, [I got the same](https://github.com/SpecFlowOSS/SpecFlow.VS/issues/18#issuecomment-977876802) since latest version.

**Comment by gasparnagy** [comment]
It seems there is a packaging problem with the latest release. We work on the hotfix that will be available in a new hours. (You need to update manually, because the automatic update will only happen tomorrow. 
We will update this issue once it is available.

**Comment by patiqs** [comment]
I just released 2021.1.4.55204 with the fix. Can you please verify?

**Comment by bromarock** [comment]
> I just released 2021.1.4.55204 with the fix. Can you please verify? https://marketplace.visualstudio.com/items?itemName=TechTalkSpecFlowTeam.SpecFlowForVisualStudio2022

It works like a charm, thanks!

.Omar

**Comment by pm90pl** [comment]
There is no possibility to manually download the extension? I mean, the problem was on a specific ver, I'm just wondering if in that case can I do a manual downgrade?

**Comment by gasparnagy** [comment]
@pm90pl In this particular issue, there is already a newer version that fixes the problem, so no need for downgrade. 

In general (so not because of this issue) you are not able to download an older version from the marketplace. However you can download the VSIX file of any version from the https://github.com/SpecFlowOSS/SpecFlow.VS/releases page. To downgrade, you need to uninstall the current version, and double click on the VSIX file to install it. In case of a downgrade, make sure you uncheck the automatic update checkbox once the downgraded version is installed otherwise VS will upgrade it to the latest again.
