### ISSUE TITLE
F12 Go to definition not working since plugin update 

### ISSUE THREAD

**Issue by infinitejest69** [SpecFlowOSS/SpecFlow.VS#30]
Plugin Version: 2021.1.2.60110
Got an Update to the plugin and the F12 navigation in Visual Studio 2022 Doesn't work.
suspect this is related to the others who have issues since update
[Other Issue](https://github.com/SpecFlowOSS/SpecFlow.VS/issues/29)

Logging as a new issue just so its not lost in the comments

**Comment by gasparnagy** [comment]
Yes it seems that this is the same issue as #29.

**Comment by infinitejest69** [comment]
happy to close if the issue will be resolved
