### ISSUE TITLE
Cannot find options in Visual Studio 2022

### ISSUE THREAD

**Issue by NesterovSergey** [SpecFlowOSS/SpecFlow.VS#37]
not sure if it is a right place but i've just started considering to move to vs 22 and after downloading SpecFlow for VS22 i was unable to find any SpecFlow settings (Tools/Options/SpecFlow) that were used in vs 19

vs version is 17.0.2
specflow is 2021.2.1.24932

**Comment by shack05** [comment]
Hello @NesterovSergey,

I too was wondering where the options went, and it looks some behaviours can now be configured via a `specflow.json` file. 

If you don't have a `specflow.json` file you can add it as follows:
```
Right click on the SpecFlow project -> Add -> New item... -> Add `SpecFlow configuration file`
```

> The configuration file has a json schema, so when you start typing you should see all available properties:
![image](https://user-images.githubusercontent.com/25411107/145645212-6e602212-2b7c-4282-adce-0f5683bcd7d8.png)

As a test I created the following configuration:
![image](https://user-images.githubusercontent.com/25411107/145645359-76051aff-a022-4e7b-bd41-b461f7cf375f.png)

I set the specflow.json file to be copied to output (this might not be necessary if you are only configuring IDE settings).

**Important** You must build your project for the changes in `specflow.json` to take effect.

After building the project I was then able to format a feature file (Ctrl + E + D) and the `And` step (line 11) is now indented as per my configuration:
![image](https://user-images.githubusercontent.com/25411107/145645647-ae7470ad-12a5-4523-9b5a-ca9a57abb1e1.png)

---

vs version is 17.0.0 Preview 4.1
specflow 2022 extension is 2021.2.1.24932

---

I can't find any docs on the specflow site however knowing that the SpecFlow VS 2022 extensions is based off the [deveroom](https://github.com/specsolutions/deveroom-visualstudio), I went looking through the deveroom wiki and found [this info about configuration](https://github.com/specsolutions/deveroom-visualstudio/wiki/Configuration).

I hope that helps.

**Comment by patiqs** [comment]
Hi @shack05,
I do like your comment with the screenshots. Do you mind if we include this into our documentation?

**Comment by shack05** [comment]
Hi @patiqs,
Yes that is fine with me.

**Comment by alimogithub** [comment]
@shack05 Thanks for this, added it to docs [https://docs.specflow.org/projects/specflow/en/latest/visualstudio/settings-options.html]
