### ISSUE TITLE
Typing performance issue

### ISSUE THREAD

**Issue by khosro** [SpecFlowOSS/SpecFlow.VS#40]
Hi 

I have typing performance issue using "SpecFlow for Visual Studio 2022" in VS 2022. I have installed version 2021.2.1.24932.
Sometime VS suggest me to disable this extension.

![Performance](https://user-images.githubusercontent.com/4457770/144803396-74d94d2d-e88b-4ed8-ac94-26e9d69c46ea.png)

I do not have this problem with "Deveroom for SpecFlow (Visual Studio 2019)" In VS 2019.  "Deveroom for SpecFlow (Visual Studio 2019)" installed version is "1.6.3"

**Comment by younggeezus** [comment]
I am having the same issue with VS 2022 too

**Comment by alimogithub** [comment]
Hi @khosro 

Thanks for raising this. We are currently working on a number of stability and performance enhancements for the plugin and I believe these would likely resolve this. If the upcoming releases don't fix this issue, we will take a deeper dive into this.
Cheers

**Comment by khosro** [comment]
@alimogithub , thanks.

 When it is available, i will try it and give feedback.

**Comment by patiqs** [comment]
Hi @khosro,
Please help me to reproduce this issue. When do you face it? What are the conditions?

**Comment by khosro** [comment]
Hi @patiqs 

Thanks for checking out the problem.

I have this problem from time to time in a project with only have one Gherkin scenario or contains many of them. 

In order to reproduce it, i created a [Specflow Project from Visual Studio Templates
](https://docs.specflow.org/projects/specflow/en/latest/Installation/Project-and-Item-Templates.html) and i wrote a few Gherkin scenarios(I wrote the Gherkin scenario and erased it and then again wrote another one and continued like this ) and it was slow while typing and after a while VS suggests me to disable `SpecFlow for Visual Studio 2022` extension as follows :

![Specflow_Perfomance](https://user-images.githubusercontent.com/4457770/146636976-fc1383f8-ff75-4c16-876a-e638d256ced6.png)


And i also found a log in `C:\Users\<UserName>\AppData\Local\SpecFlow` path and attach it here 


[specflow-vs-20211218.log](https://github.com/SpecFlowOSS/SpecFlow.VS/files/7739072/specflow-vs-20211218.log)

**It is worth to mention that i have updated `SpecFlow for Visual Studio 2022` extension to last version(2021.3.1.22551) yesterday.**

**Comment by tlecomte** [comment]
I confirm that I have a similar problem with the latest version. In my case, that's on a project that has several thousands steps. Every keystroke takes ages and makes VS unusable.

Debugging the extension seems to show that on every keystroke, it seems to recompute the tags for the current file. That seems to be a costly operation with the current implementation.

**Comment by patiqs** [comment]
Thank you for the details. Helps a lot, because we plan to do some refactoring on the tagger in the next release.

**Comment by khosro** [comment]
Thanks a lot @patiqs 

I tested new version `2022.1.4.21914` and this issue has been solved. So that i close this issue.
