### ISSUE TITLE
Visual Studio 2022 - Unable to find SpecFlow tools folder error

### ISSUE THREAD

**Issue by dcdraper** [SpecFlowOSS/SpecFlow.VS#47]
### SpecFlow Version

3.9.40

### Which test runner are you using?

NUnit

### Test Runner Version Number

3.13.2

### .NET Implementation

equal or greater .NET Framework 4.6.1

### Project Format of the SpecFlow project

Sdk-style project format

### .feature.cs files are generated using

SpecFlow.Tools.MsBuild.Generation NuGet package

### Test Execution Method

Visual Studio Test Explorer

### Issue Description

When changing a feature file and click save, an error box pops up stating that the tools folder cannot be found at .nuget\packages\specflow\3.9.40\tools but there is no tools folder there. I also get a build error even though the tests seem to run fine.
Visual Studio 2019 does not have this problem at all and no build errors either.

Message:
![image](https://user-images.githubusercontent.com/35504583/146105572-cb28f370-96d6-4af8-abc3-cda1d5a5bc28.png)

### Steps to Reproduce

Edit feature files in Visual Studio 2022 and click save.

**Comment by SabotageAndi** [comment]
@gasparnagy any ideas?

**Comment by gasparnagy** [comment]
@dcdraper @SabotageAndi Maybe the same as https://github.com/SpecFlowOSS/SpecFlow.VS/issues/28 ? I have described a solution there.

**Comment by dcdraper** [comment]
@gasparnagy 
Yes, that was it, thanks! I took the approach suggested by you in that other post to update the project file as XML and remove all references to feature files and code behind files.  This worked great, thanks!
