### ISSUE TITLE
not able to feature a file

### ISSUE THREAD

**Issue by Meeraalgun** [SpecFlowOSS/SpecFlow.VS#52]

**Comment by alimogithub** [comment]
Hi @Meeraalgun,
Can you kindly provide more details here

**Comment by Meeraalgun** [comment]
Now it is working fine after modifying visual studio

**Comment by hmakda01** [comment]
How did you fix it?

**Comment by patiqs** [comment]
I created a hotfix V2021.4.5 which includes the missing 'System.Threading.Channels.dll' to the package of the extension. Please check.
