### ISSUE TITLE
SpecRun.Runner not working after upgrading to .NET 6.0

### ISSUE THREAD

**Issue by spashaa** [SpecFlowOSS/SpecFlow.VS#55]
I upgraded the target framework to .NET 6.0 and getting these error - 
![image](https://user-images.githubusercontent.com/86250864/147766457-3b743620-ce95-4dbd-a0db-70137489b4a8.png)

**Comment by alimogithub** [comment]
@spashaa SpecFlow Runner currently does not support .NET 6. At this time I cannot give you a timeline but keep an eye on our [roadmap page ](https://docs.specflow.org/en/latest/roadmap.html?_gl=1*wbbwd6*_ga*MTY4Mzc4OTU0NC4xNjI5OTY1OTYy*_ga_BZ55XKTXC6*MTY0MTI4NDc5Ny4xMjQuMS4xNjQxMjkwMDE4LjA.&_ga=2.116061702.121596495.1641284725-1683789544.1629965962&_gac=1.262648446.1638367253.Cj0KCQiA15yNBhDTARIsAGnwe0XLIQhSNXctjxygZR_LW5dRE5g2Dpvyvab9C6Du2GfLaqrrPM5btOMaAlWNEALw_wcB)
