### ISSUE TITLE
Unable to install the IDE Integration package

### ISSUE THREAD

**Issue by Fakhraei-m** [SpecFlowOSS/SpecFlow.VS#95]
### Used Visual Studio

Visual Studio 2022

### Are the latest Visual Studio updates installed?

Yes

### Issue Description

When I try to install the IDE Integration package, either from the manage extension in VS or manually, I get this error message:

System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
at VSIXInstaller.App.SetGlobalLogger(IInteropLogger logger)
at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
at VSIXInstaller.App.Initialize()
at System.Threading.Tasks.Task`1.InnerInvoke()
at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

### Steps to Reproduce

In VS, go to Extensions > Manage Extensions > Online > Download "SpecFlow for Visual Studio 2022".
When I close the VS, it is supposed to install the Extension, but it gives the error.

when I try to download and install the package from VS marketplace, I get the same error. Here is the link to the package:
https://marketplace.visualstudio.com/items?itemName=TechTalkSpecFlowTeam.SpecFlowForVisualStudio2022&ssr=false#overview

**Comment by SabotageAndi** [comment]
@Fakhraei-m could you attach the downloaded file here?

**Comment by Fakhraei-m** [comment]
> @Fakhraei-m could you attach the downloaded file here?

I have provided the download link. 
The problem is solved now, I updated the VS and I could install it through the extension manager.

**Comment by SabotageAndi** [comment]
I wanted to have that file to have a look at it to see what you got.
Downloading was always working. We didn't change anything in the VS Marketplace.
So it could have been either an issue with the Marketplace on your side or some corporate proxy.

But good to hear that it works now for you. I am closing the issue.
